version: "3.8"
services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_backup_volume:/var/jenkins_home
      # Optional: allow Jenkins to run docker commands on the host (see warnings below)
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
  jenkins_backup_volume:
