version: "3.8"

services:
  redis:
    image: redis:7-alpine
    container_name: redis-server
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    restart: unless-stopped

  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: redis-insight
    ports:
      - "8001:8001"       # internal port - we will proxy through nginx
    restart: unless-stopped
    depends_on:
      - redis

  nginx:
    image: nginx:alpine
    container_name: redisinsight-nginx
    ports:
      - "80:80"          # Access RedisInsight via http://<host>/  (protected by basic auth)
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/htpasswd:/etc/nginx/htpasswd:ro
    depends_on:
      - redisinsight
    restart: unless-stopped

volumes:
  redis-data:

                                                                                                                                                                     37,0-1        Bot
